#!/usr/bin/env python

import sys
import os
import re

def get_repo_slug_from_origin(origin):
  origin_without_tail = re.sub('\.git$', '', origin)
  if origin_without_tail.startswith('git'):
    return origin_without_tail.split(':')[1]
  elif origin.startswith('https'):
    return '/'.join(origin_without_tail.split('/')[-2:])

def get_current_commit_id():
  return os.popen('git log --format="%H" -n 1').read().strip()

if __name__ == '__main__':
  repo_slug = get_repo_slug_from_origin(sys.argv[2])
  commit_id = get_current_commit_id()
  web_url_of_commit = '/'.join(['https://github.com', repo_slug, 'commit', commit_id])
  print(web_url_of_commit)

